name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCR_HOSTNAME: asia-northeast3-docker.pkg.dev
  BACKEND_SERVICE_NAME: lotto-backend-api
  BACKEND_REPOSITORY_NAME: lotto-backend-api
  BACKEND_IMAGE_NAME: lotto-backend-api-image
  FRONTEND_SERVICE_NAME: lotto-frontend-web
  FRONTEND_REPOSITORY_NAME: lotto-frontend-web
  FRONTEND_IMAGE_NAME: lotto-frontend-web-image
  REGION: asia-northeast3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${GCR_HOSTNAME}

      # --- Build and Deploy Backend ---
      - name: Build Backend Docker Image
        run: docker build -t ${GCR_HOSTNAME}/${PROJECT_ID}/${BACKEND_REPOSITORY_NAME}/${BACKEND_IMAGE_NAME}:${{ github.sha }} ./lotto-backend-api

      - name: Push Backend Docker Image
        run: docker push ${GCR_HOSTNAME}/${PROJECT_ID}/${BACKEND_REPOSITORY_NAME}/${BACKEND_IMAGE_NAME}:${{ github.sha }}

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy ${BACKEND_SERVICE_NAME} \
            --image ${GCR_HOSTNAME}/${PROJECT_ID}/${BACKEND_REPOSITORY_NAME}/${BACKEND_IMAGE_NAME}:${{ github.sha }} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated # Adjust as needed for authentication

      # --- Build and Deploy Frontend ---
      - name: Build Frontend Docker Image
        run: docker build -t ${GCR_HOSTNAME}/${PROJECT_ID}/${FRONTEND_REPOSITORY_NAME}/${FRONTEND_IMAGE_NAME}:${{ github.sha }} -f ./lotto-analyzer-web/Dockerfile ./lotto-analyzer-web

      - name: Push Frontend Docker Image
        run: docker push ${GCR_HOSTNAME}/${PROJECT_ID}/${FRONTEND_REPOSITORY_NAME}/${FRONTEND_IMAGE_NAME}:${{ github.sha }}

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy ${FRONTEND_SERVICE_NAME} \
            --image ${GCR_HOSTNAME}/${PROJECT_ID}/${FRONTEND_REPOSITORY_NAME}/${FRONTEND_IMAGE_NAME}:${{ github.sha }} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated # Adjust as needed for authentication